name: Cypress Tests using Cypress Docker Image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.7.0-chrome84
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1-connect-wallet/main.spec.js
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
        env:
          REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
          CYPRESS_BASE_URL: http://localhost:3000/#/
          ## !TODO! parameter took from Uniswap project and must be replaced.
          CYPRESS_WALLET_PRIVATE_KEY: ${{ secrets.CYPRESS_WALLET_PRIVATE_KEY }}

      - name: discord notification（if failure）
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
