name: E2E walk through test.

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'
  workflow_dispatch: {}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.7.0-chrome84
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/2-walk-through/main.spec.js
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
        env:
          REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
          CYPRESS_BASE_URL: http://localhost:3000/#/
          CYPRESS_WALLET_PRIVATE_KEY: ${{ secrets.CYPRESS_WALLET_PRIVATE_KEY }}

      - name: Archive test recordings
        uses: actions/upload-artifact@v2
        with:
          retention-days: 7
          name: test-recordings
          path: |
            cypress/screenshots
            cypress/videos

      - name: discord notification（if failure）
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
