name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.7.0-chrome84
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # !!TODO!! use development server
      # !!TODO!! cache components

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
        env:
          REACT_APP_NETWORK_URL: ${{ secrets.REACT_APP_NETWORK_URL }}
          CYPRESS_BASE_URL: http://localhost:3000/#/
          ## parameter took from Uniswap project
          CYPRESS_WALLET_PRIVATE_KEY: '0xe580410d7c37d26c6ad1a837bbae46bc27f9066a466fb3a66e770523b4666d19'
